version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    labels:
      nginx_proxy_companion.nginx_proxy: ""
      fluentd-tag: nginx
      co.elastic.logs/module: nginx 
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
      co.elastic.metrics/module: nginx
      co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
#    environment:
#      - TZ=Europe/Paris
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - conf.d:/etc/nginx/conf.d
      - ngproxy-vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy-net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
      
  dockergen-nginx:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -interval 86400 -watch /etc/docker-gen/templates/nginx-certbot.tmpl /etc/nginx/conf.d/default.conf
    labels:
      nginx_proxy_companion.docker_gen: ""
    environment:
      - "RESOLVERS=1.1.1.1"
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - conf.d:/etc/nginx/conf.d
      - ngproxy-vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ngproxy-tmpl:/etc/docker-gen/templates
    depends_on:
      - nginx
    networks:
      - proxy-net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  pdns-companion:
    image: poppypop/docker-pdns-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-net
    depends_on:
      - nginx
    environment:
      - "ENDPOINT=https://dns-api.mo-ot.fr"
      - "HOST_IP=10.0.1.10"
    env_file:
      - /srv/confs/pdns/env/pdns-api.env
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  nsupdate-companion:
    image: poppypop/docker-gen-nsupdate
    command: -watch -notify /nsupdate/nsupdate.sh /nsupdate/nsupdate.tmpl /tmp/nsupdate.raw
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - nsupdate-tmpl:/nsupdate:ro
    networks:
      - proxy-net
    depends_on:
      - nginx
    environment:
      - "ENDPOINT=10.0.1.1"
      - "HOST_IP=10.0.1.10"
    env_file:
      - /srv/confs/nginx-proxy/env/nsupdate.env
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
        
  certbot-companion:
    image: poppypop/docker-certbot-nginx-proxy-companion
    command: -notify /certbot/notify.sh -notify-output -notify-sighup nginx-proxy -interval 86400 -wait 300s:500s -watch /certbot/certbot-san.sh.tmpl /certbot/certbot.sh
    environment:
      - "CERTBOT_ACCOUNT=skytep@gmail.com"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt-lib:/var/lib/letsencrypt
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    depends_on:
      - nginx
    networks:
      - proxy-net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"    
 

volumes:
  letsencrypt:
    external: true
  ngproxy-tmpl:
    external: true
  conf.d:
  ngproxy-vhost:
    external: true
  html:
  letsencrypt-lib:
  nsupdate-tmpl:
    external: true  
  
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
