version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: nginx.docker.{{.ID}} 
      
  dockergen-nginx:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -interval 86400 -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/srv/confs/nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl"
    depends_on:
      - nginx
    networks:
      - proxy-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

  pdns-companion:
    image: poppypop/docker-pdns-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-net
    depends_on:
      - nginx
    environment:
      - "ENDPOINT=https://dns-api.moot.fr"
      - "HOST_IP=10.0.1.10"
    env_file:
      - /srv/confs/pdns/conf/pdns-api.env
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
        
  ssl-companion:
    image: poppypop/docker-ssl-nginx-proxy-companion
    command: -notify /docker-ssl-nginx-proxy-companion -notify-output -interval 86400 -watch /cfssl/cfssl_service_data.tmpl /cfssl/cfssl_service_data
    volumes:
      - certs:/certs
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/srv/confs/nginx-proxy/cfssl_service_data.tmpl:/cfssl/cfssl_service_data.tmpl"
    depends_on:
      - nginx
    networks:
      - proxy-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

volumes:
  certs:
    external: true
  conf.d:
  vhost.d:
  html:

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
