name: docker

metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['yugo.mo-ot.fr:9200']
  
setup.kibana:
  host: "kibana.mo-ot.fr:443"
  protocol: "https"
  ssl.enabled: true
  
setup.dashboards.enabled: true
