metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['yugo.moot.fr:9200']
  
setup.kibana:
  host: "kibana.moot.fr:443"
  protocol: "https"
  ssl.enabled: true
  ssl.certificate_authorities: ["/etc/pki/root/ca.pem", "/etc/pki/root/int.pem"]
  
setup.dashboards.enabled: true
