# WARNING: Replace the example passwords with secure secrets.
# WARNING: 'my_secret_phpipam_pass' and 'my_secret_mysql_root_pass'

version: '3'

services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    env_file:
      - env/db.env
    environment:
      - VIRTUAL_HOST=ipam.mo-ot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
      - TZ=Europe/Paris
      - IPAM_DATABASE_HOST=mariadb
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    networks:
      - proxy-net
      - default
      - ldap-backend
      - webbackend
    volumes:
      - phpipam-logo:/phpipam/css/images/logo

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    env_file:
      - env/db.env
    environment:
      - TZ=Europe/Paris
      - IPAM_DATABASE_HOST=mariadb
      - SCAN_INTERVAL=1h
    restart: unless-stopped

volumes:
  phpipam-logo:
  
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  ldap-backend:
    external: true
  webbackend:
    external: true