version: '2'

services:
    # elastic
    elastic:
        restart: always
        image: elasticsearch
        volumes:
            - /srv/docker/efk/elastic/data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
    fluent:
        restart: always
        image: poppypop/fluentd
        volumes:
            - /srv/docker/efk/fluentd:/etc/fluent
        ports:
            - 24224:24224
        depends_on:
            - elastic
        links:  
            - elastic:elasticsearch
    kibana:
        restart: always
        image: kibana
        ports:
            - 5601:5601 
        depends_on:
            - elastic
        links:  
            - elastic:elasticsearch
    