version: '3'
services:
  elastic1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - cluster.name=docker-cluster
      - path.repo=/backup
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3072m -Xmx3072m"
      - "discovery.zen.minimum_master_nodes=2"
      - node.name=elastic1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 6g
    cap_add:
      - IPC_LOCK
    volumes:
      - elastic1-datas:/usr/share/elasticsearch/data
      - elastic-backup:/backup
    ports:
      - 9200:9200
    networks:
      efk-net:
        aliases:
          - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  elastic2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - cluster.name=docker-cluster
      - path.repo=/backup
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3072m -Xmx3072m"
      - "discovery.zen.ping.unicast.hosts=elastic1"
      - node.name=elastic2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 6g
    cap_add:
      - IPC_LOCK
    networks:
      - efk-net
    volumes:
      - elastic2-datas:/usr/share/elasticsearch/data
      - elastic-backup:/backup
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  fluentd:
    image: poppypop/docker-fluentd
    container_name: docker-fluentd
    ports:
      - 24224:24224
    volumes:
      - fluentd-conf:/fluentd/etc/:ro
      - /var/lib/docker/containers/:/docker/containers/:ro
      - fluentd-logpos:/fluentd/logpos/
    environment:
      - FLUENTD_CONF=fluentd.conf
      - FLUENT_UID=0
    networks:
      - efk-net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
        
  fluentd-gen:
    image: jwilder/docker-gen
    command: -notify-sighup docker-fluentd -interval 86400 -watch /fluentd/etc/docker-log.tmpl /fluentd/etc/docker-log.conf
    volumes:
      - fluentd-conf:/fluentd/etc/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
        
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - VIRTUAL_HOST=kibana.mo-ot.fr
      - VIRTUAL_PORT=5601
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    depends_on:
      - elastic1
      - elastic2
    networks:
      - proxy-net
      - efk-net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
        
networks:
  proxy-net:
    external: true
  efk-net:
    external: true

volumes:
  elastic1-datas:
    external: true
  elastic2-datas:
    external: true
  elastic-backup:
    external: true
  fluent-conf:
    external: true
  fluentd-conf:
    external: true
  fluentd-logpos:
    