version: '2'

services:
    # elastic
    elastic:
        restart: always
        image: elasticsearch
        environment:
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
        volumes:
            - /srv/confs/efk/elastic:/usr/share/elasticsearch/config
            - /srv/datas/efk/elastic:/usr/share/elasticsearch/data
            - /srv/datas/efk/backs-elastic:/backup
        ports:
            - 9200:9200
            - 9300:9300
        logging:
            driver: json-file
            options:
                max-size: "50m"
                max-file: "7"
    fluent:
        restart: always
        image: poppypop/fluentd
        volumes:
            - /srv/confs/efk/fluentd:/etc/fluent
        ports:
            - 24224:24224
        depends_on:
            - elastic
        links:  
            - elastic:elasticsearch
        logging:
            driver: json-file
            options:
                max-size: "50m"
                max-file: "7"
    kibana:
        restart: always
        image: kibana
        ports:
            - 5601:5601 
        depends_on:
            - elastic
        links:  
            - elastic:elasticsearch
        logging:
            driver: json-file
            options:
                max-size: "50m"
                max-file: "7"

