version: '3'

services:
  emby:
    image: emby/embyserver_netcore:latest
    environment:
      - VIRTUAL_HOST=emby.moot.fr
      - VIRTUAL_PORT=8096
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
      - UID=11001
      - GID=11002
      - GIDLIST=513
    volumes:
      - emby-datas:/config
      - "/datas:/datas"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    networks:
      - proxy-net
      - default
    #ports:
    #  - "8096:8096"
    #  - "8920:8920"
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "127.0.0.1:24224" 
#        fluentd-async-connect: "true"
#        tag: docker.{{.ID}} 


volumes:
  emby-datas:
    external: true

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
