version: '3'

services:
  emby:
    image: emby/embyserver:beta
    environment:
      - VIRTUAL_HOST=emby.moot.fr
      - VIRTUAL_PORT=8096
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
      - HTTPS_METHOD=noredirect
      - UID=11001
      - GID=11002
      - GIDLIST=513,44
    volumes:
      - emby-datas:/config
      - emby-local-datas:/datas
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    networks:
      - proxy-net
      - default
#    ports:
#      - 7359:7359/udp
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 


volumes:
  emby-datas:
    external: true
  emby-local-datas:
    external: true

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
