version: '3'

networks:
  webbackend:
    external: true
  proxy-net:
    external: true
    
volumes:
  jeedom-datas:
    external: true  
    
services:
  
  jeedom:
    image: jeedom/jeedom
    env_file:
      - env/jeedom.env
    environment:
      - VIRTUAL_HOST=jeedom.mo-ot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    volumes:
      - jeedom-datas:/var/www/html
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
#    ports:
#      - 9022:22
    networks:
      proxy-net:
      webbackend:
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
