version: '3'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "127.0.0.1:24224"
#        fluentd-async-connect: "true"
#        tag: docker.{{.ID}}
        
  app:  
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud-base:/var/www/html
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
    env_file:
      - db.env
    depends_on:
      - redis
    networks:
      - webbackend
      - ldap-backend
      - default
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "127.0.0.1:24224"
#        fluentd-async-connect: "true"
#        tag: docker.{{.ID}}

  web:
    image: nginx
    volumes:
      - nextcloud-base:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST=cloud.moot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    depends_on:
      - app
    networks:
      - proxy-net
      - default
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "127.0.0.1:24224"
#        fluentd-async-connect: "true"
#        tag: docker.{{.ID}}

  cron:
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud-data:/var/www/html
    user: www-data
    entrypoint: |
      sh -c 'sh -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM

        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1m
        done

        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'
    depends_on:
      - redis
    networks:
      - webbackend
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "127.0.0.1:24224"
#        fluentd-async-connect: "true"
#        tag: docker.{{.ID}}

volumes:
  nextcloud-data:
    external: true
  nextcloud-base:
    external: true
  nextcloud-apps:
    external: true
  nextcloud-config:
    external: true
  redis-data:

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  webbackend:
    external: true
  ldap-backend:
    external: true
