version: '3'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
              
  app:  
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud-base:/var/www/html
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
      - alpine-certs:/etc/ssl/certs:ro
    env_file:
      - env/db.env
    depends_on:
      - redis
    networks:
      - webbackend
      - ldap-backend
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  web:
    image: nginx:alpine
    labels:
      fluentd-tag: nginx
      co.elastic.logs/module: nginx 
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
      co.elastic.metrics/module: nginx
      co.elastic.metrics/hosts: "${data.host}:${data.port}"
    volumes:
      - nextcloud-base:/var/www/html:ro
      - nextcloud-nginx:/etc/nginx/conf.d:ro
      - alpine-certs:/etc/ssl/certs:ro
    environment:
      - VIRTUAL_HOST=cloud.mo-ot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    depends_on:
      - app
    networks:
      - proxy-net
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  cron:
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud-base:/var/www/html
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
      - alpine-certs:/etc/ssl/certs:ro
    env_file:
      - env/db.env
    user: www-data
    entrypoint: |
      sh -c 'sh -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        while [ ! -f /var/www/html/config/config.php ]; do
          echo "Waiting for /var/www/html/config/config.php"
          sleep 1m
        done

        while true; do
          echo "Executing Cron"
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'
    depends_on:
      - redis
    networks:
      - webbackend
      - ldap-backend
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

volumes:
  nextcloud-data:
    external: true
  nextcloud-base:
    external: true
  nextcloud-apps:
    external: true
  nextcloud-config:
    external: true
  alpine-certs:
    external: true  
  nextcloud-nginx:
    external: true  
  redis-data:

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  webbackend:
    external: true
  ldap-backend:
    external: true
