version: '3'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}
        
  app:  
    image: poppypop/nextcloud-app
    volumes:
      - nextcloud-data:/var/www/html
    env_file:
      - db.env
    depends_on:
      - redis
    networks:
      - webbackend
      - ldap-backend
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}

  web:
    image: poppypop/nextcloud-web
    volumes:
      - nextcloud-data:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=cloud.yugo.moot
      - VIRTUAL_PORT=80
#      - LETSENCRYPT_HOST=cloud.yugo.moot
#      - LETSENCRYPT_EMAIL=cloud@moot
    depends_on:
      - app
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}

  cron:
    image: poppypop/nextcloud-app
    volumes:
      - nextcloud-data:/var/www/html
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM

        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1m
        done

        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'
    depends_on:
      - redis
    networks:
      - webbackend
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}

volumes:
  nextcloud-data:
    external: true
  redis-data:

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  webbackend:
    external: true
  ldap-backend:
    external: true
