version: '3'

volumes:
  aria-datas:
    external: true
  certs:
    external: true
  alpine-certs:
    external: true

services:
  aria2:
    image: poppypop/aria2-alpine
    environment:
      - SPLIT=8
      - CONNECTIONS_PER_SERVER=8
      - CONCURRENT_DOWNLOADS=5
      - DOWNLOAD_DIR=/datas/Downloads
      - SESSION_FILE=/datas/aria2.session
      - RPC_SECURE=true
      - RPC_CERT=/certs/aria.mo-ot.fr.crt
      - RPC_PRIV_KEY=/certs/aria.mo-ot.fr.key
      - RPC_SECRET=5up5YSxf74AVE4w
    volumes:
      - aria-datas:/datas
      - certs:/certs
      - alpine-certs:/etc/ssl/certs:ro
    user: 1001:1001
    networks:
      default:
        aliases:
          - aria.mo-ot.fr
    ports:
      - "6800:6800"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
  
  httpd:
    image: poppypop/aria2-webui
    environment:
      - VIRTUAL_HOST=aria.mo-ot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
      - RPC_SECRET=5up5YSxf74AVE4w
    networks:
      - proxy-net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
      
  go-automated-ended:
    image: poppypop/go-automate-ended
    command: ["/app/go-automate-ended", "-addr", "aria.mo-ot.fr:6800", "-token", "5up5YSxf74AVE4w"]
    volumes:
      - aria-datas:/datas 
      - alpine-certs:/etc/ssl/certs:ro
    user: 1001:1001
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
