version: '3'

volumes:
  aria-datas:
    external: true

services:
  aria2:
    image: poppypop/aria2:alpine
    environment:
      - SPLIT=8
      - CONNECTIONS_PER_SERVER=8
      - CONCURRENT_DOWNLOADS=5
      - DOWNLOAD_DIR=/datas/Downloads
      #- COMPLETE_HOOK=/datas/complete.sh
    volumes:
      -  aria-datas:/datas
    ports:
      - "6800:6800"
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
  
  httpd:
    image: poppypop/aria2-webui
    environment:
      - VIRTUAL_HOST=aria.moot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
  go-automated-ended:
    image: poppypop/go-automated-ended
    volumes:
      - aria-datas:/datas 
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
