aria2:
    image: poppypop/aria2-alpine
    environment:
      - SPLIT=8
      - CONNECTIONS_PER_SERVER=8
      - CONCURRENT_DOWNLOADS=5
      - RPC_SECRET=reMgE94K5cSiE926
    volumes:
        - /srv/webui-aria2/Downloads:/downloads
    ports:
        - "6800:6800"

httpd:
    image: busybox
    volumes:
        - ./webui-aria2:/usr/html
    ports:
        - "9100:80"
    command: /bin/busybox httpd -f -p 80 -h /usr/html
