version: '3'

volumes:
  aria-datas:
    external: true
  certs:
    external: true

services:
  aria2:
    image: poppypop/aria2-alpine
    environment:
      - SPLIT=8
      - CONNECTIONS_PER_SERVER=8
      - CONCURRENT_DOWNLOADS=5
      - DOWNLOAD_DIR=/datas/Downloads
      - SESSION_FILE=/datas/aria2.session
      - RPC_SECURE=true
      - RPC_CERT=/certs/aria.moot.fr.crt
      - RPC_PRIV_KEY=/certs/aria.moot.fr.key
    volumes:
      -  aria-datas:/datas
      -  certs:/certs
    user: 1001:1001
    ports:
      - "6800:6800"
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
  
  httpd:
    image: poppypop/aria2-webui
    environment:
      - VIRTUAL_HOST=aria.moot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
  go-automated-ended:
    image: poppypop/go-automated-ended
    volumes:
      - aria-datas:/datas 
    user: 1001:1001
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
