version: '3'

volumes:
  aria-downloads:
    external: true
  aria-ended:
    external: true
  aria-extract:
    external: true
  aria-atrier:
    external: true

services:
  aria2:
    image: poppypop/aria2:alpine
    environment:
      - SPLIT=8
      - CONNECTIONS_PER_SERVER=8
      - CONCURRENT_DOWNLOADS=5
      - COMPLETE_HOOK=/downloads/complete.sh
    volumes:
      - aria-downloads:/downloads
    ports:
      - "6800:6800"
  
  httpd:
    image: poppypop/aria2-webui
    environment:
      - VIRTUAL_HOST=aria.yugo.moot
      - VIRTUAL_PORT=8080
    networks:
      - proxy-net
      
  go-automated-ended:
    image: poppypop/go-automated-ended
    volumes:
      - aria-downloads:/downloads 
      - aria-ended:/ended 
      - aria-extract:/extract 
      - aria-atrier:/nfs:nocopy

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true