version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=mariadb
      - VIRTUAL_HOST=mysql.mo-ot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - webbackend
      - proxy-net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  webbackend:
    external: true
