version: '3'

networks:
  proxy-net:
    external: true

volumes:
  trakt-datas:
    external: true
    
services:
  trakt-web:
    image: poppypop/trakt-web
    volumes:
      - trakt-datas:/datas
    environment:
      - VIRTUAL_HOST=trakt.mo-ot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
      #- ASPNETCORE_ENVIRONMENT=Development
    networks:
      - proxy-net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

