version: '3'

services:
  db:
    image: mariadb
    #restart: always
    env_file:
      - conf/db.env
    volumes:
      - pdns-mysql:/var/lib/mysql
    networks:
      default:
        aliases:
          - mysql
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
  adminer:
    image: adminer
    #restart: always
    environment:
      - VIRTUAL_HOST=dns-mysql.moot.fr
      - VIRTUAL_PORT=8080
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

  pdns-recursor:
    image: pschiffe/pdns-recursor:alpine
    ports:
      - "53:53"
      - "53:53/udp"
    environment:
      - VIRTUAL_HOST=dns-recursor.moot.fr
      - VIRTUAL_PORT=8080
    expose:
      - 8080
    env_file:
      - conf/pdns-api.env
      - conf/pdns-recursor.env
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
  pdns:
    image: pschiffe/pdns-mysql:alpine
    #restart: always
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=dns-api.moot.fr
      - VIRTUAL_PORT=8080
    expose:
      - 8080
    env_file:
      - conf/pdns.env
      - conf/pdns-api.env
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
  pdns-recursor-companion :
    image: poppypop/docker-pdns-recursor-companion   
    env_file:
      - conf/pdns-api.env
    depends_on:
      - pdns
      - pdns-recursor
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi:alpine
    volumes:
      - pdns-admin-upload:/opt/powerdns-admin/upload
    depends_on:
      - pdns
    env_file:
      - conf/pdns-admin.env
    networks:
      - ldap-backend
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

  pdns-admin-static:
    image: pschiffe/pdns-admin-static
    depends_on:
      - pdns-admin-uwsgi
    environment:
      - VIRTUAL_HOST=dns.moot.fr
      - VIRTUAL_PORT=80
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
volumes:
  pdns-mysql:
    external: true
  pdns-admin-upload:
    external: true

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  ldap-backend:
    external: true
