version: '3'

services:
  pgsql:
    image: postgres:alpine
    #restart: always
    env_file:
      - env/db.env
    volumes:
      - pdns-pgsql:/var/lib/postgresql/data
    networks:
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}
      
  adminer:
    image: adminer
    #restart: always
    environment:
      - VIRTUAL_HOST=dns-sql.moot.fr
      - VIRTUAL_PORT=8080
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

  pdns-recursor:
    image: pschiffe/pdns-recursor:alpine
    ports:
      - "53:53"
      - "53:53/udp"
    environment:
      - VIRTUAL_HOST=dns-recursor.moot.fr
      - VIRTUAL_PORT=8080
    expose:
      - 8080
    env_file:
      - env/pdns-api.env
      - env/pdns-recursor.env
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
  pdns:
    image: poppypop/docker-pdns
    #restart: always
    depends_on:
      - pgsql
    environment:
      - VIRTUAL_HOST=dns-api.moot.fr
      - VIRTUAL_PORT=8080
    expose:
      - 8080
    env_file:
      - env/pdns.env
      - env/pdns-api.env
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
  pdns-recursor-companion :
    image: poppypop/docker-pdns-recursor-companion   
    env_file:
      - env/pdns-api.env
    depends_on:
      - pdns
      - pdns-recursor
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
  pdns-admin-uwsgi:
    image: poppypop/docker-pdns-admin-uwsgi
    volumes:
      - pdns-admin-upload:/opt/powerdns-admin/upload
      - pdns-admin-db:/opt/powerdns-admin/db
    depends_on:
      - pdns
    env_file:
      - env/pdns-admin.env
    networks:
      - ldap-backend
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

  pdns-admin-static:
    image: pschiffe/pdns-admin-static
    depends_on:
      - pdns-admin-uwsgi
    environment:
      - VIRTUAL_HOST=dns.moot.fr
      - VIRTUAL_PORT=80
    ports:
      - 1256:80
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 
      
volumes:
  pdns-pgsql:
    external: true
  pdns-admin-upload:
    external: true
  pdns-admin-db:

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  ldap-backend:
    external: true
