version: '3'

services:
  pgsql:
    image: postgres:alpine
    #restart: always
    env_file:
      - env/db.env
    volumes:
      - pdns-pgsql:/var/lib/postgresql/data
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
      
  adminer:
    image: adminer
    #restart: always
    environment:
      - VIRTUAL_HOST=dns-sql.mo-ot.fr
      - VIRTUAL_PORT=8080
    networks:
      - proxy-net
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  pdns-recursor:
    image: pschiffe/pdns-recursor:alpine
    ports:
      - "53:53"
      - "53:53/udp"
    environment:
      - VIRTUAL_HOST=dns-recursor.mo-ot.fr
      - VIRTUAL_PORT=8080
    expose:
      - 8080
    env_file:
      - env/pdns-api.env
      - env/pdns-recursor.env
    volumes:
      - pdns-lua-conf:/etc/pdns/lua
    networks:
      - proxy-net
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
      
  pdns:
    image: poppypop/docker-pdns
    #restart: always
    depends_on:
      - pgsql
    environment:
      - VIRTUAL_HOST=dns-api.mo-ot.fr
      - VIRTUAL_PORT=8080
    expose:
      - 8080
    env_file:
      - env/pdns.env
      - env/pdns-api.env
    networks:
      - proxy-net
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
      
  pdns-recursor-companion :
    image: poppypop/docker-pdns-recursor-companion   
    env_file:
      - env/pdns-api.env
    depends_on:
      - pdns
      - pdns-recursor
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
        
  pdns-cleaner :
    image: poppypop/go-pdns-cleaner   
    env_file:
      - env/pdns-api.env
    environment:
      - PDNS_DOMAIN=mo-ot.fr
      - PDNS_API_SERVER=http://pdns:8080
    depends_on:
      - pdns
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
      
  pdns-admin-uwsgi:
    image: poppypop/docker-pdns-admin-uwsgi
    volumes:
      - pdns-admin-upload:/opt/powerdns-admin/upload
      - pdns-admin-db:/opt/powerdns-admin/db
    depends_on:
      - pdns
    env_file:
      - env/pdns-admin.env
    networks:
      - ldap-backend
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  pdns-admin-static:
    image: pschiffe/pdns-admin-static
    depends_on:
      - pdns-admin-uwsgi
    environment:
      - VIRTUAL_HOST=dns.mo-ot.fr
      - VIRTUAL_PORT=80
    networks:
      - proxy-net
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
      
volumes:
  pdns-pgsql:
    external: true
  pdns-admin-upload:
    external: true
  pdns-admin-db:
    external: true
  pdns-lua-conf:
    external: true

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  ldap-backend:
    external: true
