version: '3'

services:
  db:
    image: mariadb
    #restart: always
    env_file:
      - db.env
    volumes:
      - pdns-mysql:/var/lib/mysql
    networks:
      default:
        aliases:
          - mysql
      
  adminer:
    image: adminer
    #restart: always
    environment:
      - VIRTUAL_HOST=dns-mysql.yugo.moot
      - VIRTUAL_PORT=8080
    networks:
      - proxy-net
      - default

  pdns-recursor:
    image: pschiffe/pdns-recursor:alpine
    ports:
      - "53:53"
      - "53:53/udp"
    environment:
      - VIRTUAL_HOST=dns-recursor.yugo.moot
      - VIRTUAL_PORT=8080
    volumes:
      - pdns-recursor-datas:/etc/pdns
    expose:
      - 8080
    env_file:
      - pdns-api.env
      - pdns-recursor.env
    networks:
      - proxy-net
      - default
      
  pdns:
    image: pschiffe/pdns-mysql:alpine
    #restart: always
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=dns-api.yugo.moot
      - VIRTUAL_PORT=8080
    expose:
      - 8080
    env_file:
      - pdns.env
      - pdns-api.env
    networks:
      - proxy-net
      - default
      
  pdns-recursor-companion :
    image: poppypop/docker-pdns-recursor-companion   
    env_file:
      - pdns-api.env
    depends_on:
      - pdns
      - pdns-recursor
      
  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi:alpine
    volumes:
      - pdns-admin-upload:/opt/powerdns-admin/upload
    depends_on:
      - pdns
    env_file:
      - pdns-admin.env
    networks:
      - ldap-backend
      - default

  pdns-admin-static:
    image: pschiffe/pdns-admin-static
    depends_on:
      - pdns-admin-uwsgi
    environment:
      - VIRTUAL_HOST=dns.yugo.moot
      - VIRTUAL_PORT=80
    networks:
      - proxy-net
      - default
      


volumes:
  pdns-mysql:
    external: true
  pdns-admin-upload:
    external: true
  pdns-recursor-datas:
    external: true

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  ldap-backend:
    external: true
