version: '2'

networks:
    webbackend:
        external: true
        
services:
    # mariadb
    mariadb:
        restart: always
        image: mariadb
        volumes:
            - /srv/docker/mariadb/data:/var/lib/mysql
            - /srv/docker/mariadb/config:/etc/mysql/conf.d
        ports:
            - 3306:3306
        networks:
            webbackend:
                aliases:
                    - mariadb
        logging:
            driver: fluentd
            options:
                fluentd-address: "127.0.0.1:24224" 
                fluentd-async-connect: "true"