version: '3'

networks:
  webbackend:
    external: true
  proxy-net:
    external: true
    
volumes:
  mariadb-config:
    external: true
  mariadb-datas:
    external: true    
    
services:
  adminer:
    image: adminer
    #restart: always
    environment:
      - VIRTUAL_HOST=mysql.mo-ot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7" 
  # mariadb
  mariadb:
    image: mariadb
    env_file:
      - env/db.env
    volumes:
      - mariadb-datas:/var/lib/mysql
      - mariadb-config:/etc/mysql/conf.d/:ro
    ports:
      - 3306:3306
    networks:
      default:
      webbackend:
        aliases:
          - mariadb
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
