version: '3'

services:
  openldap:
    image: poppypop/docker-openldap
    volumes:
      - openldap-data:/var/lib/openldap/openldap-data
      - openldap-config:/etc/openldap/slapd.d
      - alpine-certs:/etc/ssl/certs:ro
      - openldap-certs:/etc/ssl/ldap:ro
    networks:
      - ldap-backend
    ports:
      - 389:389
      - 636:636
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}
  fd:
    image: poppypop/docker-fusiond
    volumes:
      - debian-certs:/etc/ssl/certs:ro
      - fusiond-config:/etc/fusiondirectory/
    environment:
      - VIRTUAL_HOST=ldap.mo-ot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - ldap-backend
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}    

volumes:
  openldap-data:
    external: true
  openldap-config:
    external: true
  openldap-certs:
    external: true  
  alpine-certs:
    external: true  
  debian-certs:
    external: true  
  fusiond-config:
    external: true  
        
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  ldap-backend:
    external: true
