version: '3'

services:
  openldap:
    image: poppypop/docker-openldap
    restart: on-failure
    volumes:
      - openldap-data:/var/lib/openldap/openldap-data
      - openldap-config:/etc/openldap/slapd.d
      - letsencrypt:/etc/letsencrypt:ro
    environment:
      - LOGLEVEL=256
    networks:
      ldap-backend:
        aliases:
          - ldap.mo-ot.fr
    ports:
      - 389:389
      - 636:636
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
        
  fd:
    image: poppypop/docker-fusiond
    volumes:
      - fusiond-config:/etc/fusiondirectory/
    environment:
      - VIRTUAL_HOST=ldap.mo-ot.fr
      - VIRTUAL_PORT=80
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - ldap-backend
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"   

volumes:
  openldap-data:
    external: true
  letsencrypt:
    external: true
  openldap-config:
    external: true
  fusiond-config:
    external: true  
        
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  ldap-backend:
    external: true
