version: '3'

services:
  openldap:
    image: poppypop/docker-openldap
    volumes:
      - openldap-data:/var/lib/openldap/openldap-data
      - openldap-config:/etc/openldap/slapd.d
      - /etc/ssl:/etc/ssl:ro
    networks:
      - ldap-backend
    ports:
      - 389:389
      - 636:636
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}
  fd:
    image: poppypop/docker-fusiond
    volumes:
      - /etc/ssl:/etc/ssl:ro
      - /srv/confs/ldap/fusiondirectory.conf:/etc/fusiondirectory/fusiondirectory.conf:ro
    environment:
      - VIRTUAL_HOST=ldap.yugo.moot
      - VIRTUAL_PORT=80
    networks:
      - proxy-net
      - ldap-backend
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}    

volumes:
  openldap-data:
    external: true
  openldap-config:
    external: true
        
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
  ldap-backend:
    external: true
