version: '3'

services:
  openldap:
    image: poppypop/ldap
    volumes:
      - openldap-data:/var/lib/openldap/openldap-data
      - /etc/ssl:/etc/ssl:ro
    ports:
      - 389:389
      - 636:636
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}
  fd:
    image: poppypop/fusiond
    volumes:
      - /etc/ssl:/etc/ssl:ro
    environment:
      - VIRTUAL_HOST=ldap.yugo.moot
      - VIRTUAL_PORT=80
    networks:
      - proxy-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}    

volumes:
  openldap-data:
    external: true
        
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true