version: '3'

services:
  openldap:
    image: poppypop/docker-openldap
    env_file:
      #- openldap/slapd.env
      - openldap/slapd.ssl.env
    #environment:
      #- SLAPCONFIG=/etc/openldap/config.ldif
      #- DEBUG=1
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - openldap-data:/var/lib/openldap/openldap-data
      - openldap-config:/etc/openldap/slapd.d
      - ${PWD}/openldap/config.ldif:/etc/openldap/config.ldif:ro

volumes:
  openldap-data:
    external: true
  openldap-config:
    external: true
  letsencrypt:
    external: true
