version: '3'

services:
  openldap:
    image: poppypop/docker-openldap
    env_file:
      - openldap/slapd.env
    environment:
      - SLAPCONFIG=/etc/openldap/config.ldif
    volumes:
      - /etc/ssl:/etc/ssl:ro
      - openldap-data:/var/lib/openldap/openldap-data
      - openldap-config:/etc/openldap/slapd.d
      - ${PWD}/openldap/config.ldif:/etc/openldap/config.ldif:ro
  fd:
    image: poppypop/docker-fusiond
    env_file:
      - fusiondirectory/fusiondirectory.env
    volumes:
      - /etc/ssl:/etc/ssl:ro
      - ${PWD}/fusiondirectory/fusiondirectory.conf:/etc/fusiondirectory/fusiondirectory.conf:ro

volumes:
  openldap-data:
    external: true
  openldap-config:
    external: true
