version: '3'

services:
  ddns:
    image: poppypop/docker-ddns
    env_file:
      - env/ddns.env
    volumes:
      - ddns-datas:/conf
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

volumes:
  ddns-datas:

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
