version: '2'
services:
  elastic:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      - cluster.name=docker-cluster
      - path.repo="/backup"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.minimum_master_nodes: 1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /srv/datas/efk/elastic1:/usr/share/elasticsearch/data
      - /srv/backs/efk/elastic1:/backup
    ports:
      - 9200:9200
    networks:
      - esnet
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
        
  fluent:
    restart: always
    image: poppypop/fluentd:alpine
    ports:
      - 24224:24224
    depends_on:
      - elastic
    networks:
      - esnet
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
        
  kibana-n:
    restart: always
    image: docker.elastic.co/kibana/kibana:5.3.0
    ports:
      - 5601:5601 
    depends_on:
      - elastic
    networks:
      - esnet
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
        
networks:
  esnet:
    driver: bridge
