version: '2'
        
services:
  transmission:
    image: linuxserver/transmission
    environment: 
      - TZ=Europe/Paris
      #- PGID=1001
      #- PUID=1001
      - VIRTUAL_HOST=transmission.mo-ot.fr
      - VIRTUAL_PORT=9091
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    volumes:
      - transmission-datas:/downloads
      - transmission-watch:/watch
      - transmission-conf:/config
    ports:
      - 51413:51413
      - 51413:51413/udp
    networks:
      - proxy-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}
        
volumes:
  transmission-watch:
  transmission-datas:
    external: true
  transmission-conf:
    external: true
    
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
