version: '2'
        
services:
  transmission:
    image: linuxserver/transmission
    environment: 
      - TZ=Europe/Paris
      - PGID=1001
      - PUID=1001
    volumes:
      - /downloads/transmission:/downloads
      - transmission-watch:/watch
      - /srv/confs/transmission:/config
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}
        
volumes:
  transmission-watch:
    
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000