version: '2'
        
services:
  transmission:
    image: linuxserver/transmission
    environment: 
      - TZ=Europe/Paris
      #- PGID=1001
      #- PUID=1001
      - VIRTUAL_HOST=transmission.moot.fr
      - VIRTUAL_PORT=9091
    volumes:
      - /datas/downloads/transmission:/downloads
      - transmission-watch:/watch
      - /srv/confs/transmission:/config
    ports:
      - 51413:51413
      - 51413:51413/udp
    networks:
      - proxy-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}
        
volumes:
  transmission-watch:
    
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
