version: '3'

services:
  db:
    image: postgres:alpine
    #restart: always
    env_file:
      - env/db.env
    volumes:
      - kea-pgsql:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:3199:5432"
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}

  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=kea-sql.moot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

  kea:
    image: poppypop/docker-kea:pgsql
    depends_on:
      - db
    env_file:
      - env/kea.env
    volumes:
      - kea-socket:/run/kea/sockets/
      - alpine-certs:/etc/ssl/certs:ro
      - kea-conf:/etc/kea/
    network_mode: "host"
    environment:
      - KEA_IFACE=enp1s0
      - DB_PORT=3199
      - DB_HOST=127.0.0.1
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

  kea-control-agent:
    image: poppypop/docker-kea:pgsql
    command: kea-ctrl-agent
    environment:
      - VIRTUAL_HOST=kea-api.moot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - default
    depends_on:
      - kea
    volumes:
      - kea-socket:/run/kea/sockets/
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 


volumes:
  kea-pgsql:
    external: true
  alpine-certs:
    external: true
  kea-socket:
  kea-conf:
    external: true
    
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
