version: '3'

services:
  db:
    image: mariadb
    #restart: always
    env_file:
      - db.env
    volumes:
      - kea-mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:9306:3306"
      
  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=kea-mysql.yugo.moot
      - VIRTUAL_PORT=8080
    networks:
      - proxy-net
      - default

  kea:
    image: poppypop/docker-kea
    network_mode: "host"
    depends_on:
      - db
    env_file:
      - kea.env


volumes:
  kea-mysql:
    external: true

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
