version: '3'

services:
  db:
    image: postgres:alpine
    #restart: always
    env_file:
      - env/db.env
    volumes:
      - kea-pgsql:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:3199:5432"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=kea-sql.mo-ot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - default
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  kea:
    image: poppypop/docker-kea:latest
    depends_on:
      - db
    env_file:
      - env/kea.env
    volumes:
      - kea-socket:/run/kea/sockets/
      - alpine-certs:/etc/ssl/certs:ro
      - kea-conf:/etc/kea/
    network_mode: "host"
    environment:
      - KEA_IFACE=\"enp2s0\", \"wlp3s0\"
      - DB_PORT=3199
      - DB_HOST=127.0.0.1
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  kea-control-agent:
    image: poppypop/docker-kea:latest
    command: kea-ctrl-agent
    environment:
      - VIRTUAL_HOST=kea-api.mo-ot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - default
    depends_on:
      - kea
    volumes:
      - kea-socket:/run/kea/sockets/
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"


volumes:
  kea-pgsql:
    external: true
  alpine-certs:
    external: true
  kea-socket:
  kea-conf:
    external: true
    
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
