version: '3'

services:
  db:
    image: mariadb
    #restart: always
    env_file:
      - db.env
    volumes:
      - kea-mysql:/var/lib/mysql
      
  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=kea-mysql.moot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - default

  kea:
    image: poppypop/docker-kea
    depends_on:
      - db
    env_file:
      - kea.env
    volumes:
      - kea-socket:/run/kea/sockets/
      - ${PWD}/hook.sh:/hook.sh:ro
      - ${PWD}/kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf:ro
    ports:
      - "9067:67/udp"

  kea-relay:
    image: poppypop/docker-kea
    network_mode: "host"
    volumes:
      - ${PWD}/kea-dhcp4-relay.conf:/etc/kea/kea-dhcp4.conf:ro

  kea-control-agent:
    image: poppypop/docker-kea
    command: kea-ctrl-agent
    environment:
      - VIRTUAL_HOST=kea-api.moot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    depends_on:
      - kea
    volumes:
      - kea-socket:/run/kea/sockets/


volumes:
  kea-mysql:
    external: true
  kea-socket:

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
