version: '3'

services:
  db:
    image: mariadb
    #restart: always
    env_file:
      - /srv/confs/kea/db.env
    volumes:
      - kea-mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3198:3306"

  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=kea-mysql.moot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - default

  kea:
    image: poppypop/docker-kea
    depends_on:
      - db
    env_file:
      - /srv/confs/kea/kea.env
    volumes:
      - kea-socket:/run/kea/sockets/
      - /srv/confs/kea/hook.sh:/hook.sh:ro
      - /srv/confs/kea/kea-dhcp4/:/etc/kea/
    network_mode: "host"
    environment:
      - KEA_IFACE=ens34
      - DB_PORT=3198
      - DB_HOST=127.0.0.1
#    ports:
#      - "192.168.0.118:167:67/udp"
#      - "192.168.0.118:167:67"

#  kea-relay:
#    image: poppypop/docker-dhcrelay
#    depends_on:
#      - kea
#    network_mode: "host"
#    environment:
#      - DHCRELAY_IFACE=ens34
#      - DHCRELAY_CIRCUIT=1
#      - DHCRELAY_DROP=1
#      - DHCRELAY_SERVERS=192.168.0.118

  kea-control-agent:
    image: poppypop/docker-kea
    command: kea-ctrl-agent
    environment:
      - VIRTUAL_HOST=kea-api.moot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    depends_on:
      - kea
    volumes:
      - kea-socket:/run/kea/sockets/


volumes:
  kea-mysql:
    external: true
  kea-socket:

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
