version: '3'

services:
  db:
    image: mariadb
    #restart: always
    env_file:
      - /srv/confs/kea/db.env
    volumes:
      - kea-mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3198:3306"
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}}   

  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=kea-mysql.moot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - default
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

  kea:
    image: poppypop/docker-kea
    depends_on:
      - db
    env_file:
      - /srv/confs/kea/kea.env
    volumes:
      - kea-socket:/run/kea/sockets/
      - /srv/confs/kea/hook.sh:/hook.sh:ro
      - /srv/confs/kea/kea-dhcp4/:/etc/kea/
    network_mode: "host"
    environment:
      - KEA_IFACE=eno1
      - DB_PORT=3198
      - DB_HOST=127.0.0.1
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 

  kea-control-agent:
    image: poppypop/docker-kea
    command: kea-ctrl-agent
    environment:
      - VIRTUAL_HOST=kea-api.moot.fr
      - VIRTUAL_PORT=8080
      - PUBLISH_DNS=1
      - PUBLISH_DNS_TXT=1
    networks:
      - proxy-net
      - default
    depends_on:
      - kea
    volumes:
      - kea-socket:/run/kea/sockets/
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224" 
        fluentd-async-connect: "true"
        tag: docker.{{.ID}} 


volumes:
  kea-mysql:
    external: true
  kea-socket:

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
  proxy-net:
    external: true
