metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['yugo.mo-ot.fr:9200']
  
setup.kibana:
  host: "kibana.mo-ot.fr:443"
  protocol: "https"
  ssl.enabled: true

setup.dashboards.enabled: true
