version: '3'

networks:
  webbackend:
    external: true
  proxy-net:
    external: true

volumes:
  web-datas:
    external: true
  web-conf:
    external: true
    
services:
  # PHPFpm
  php-fpm:
    image: poppypop/php-fpm
    volumes:
      - web-datas:/srv/http
    networks:
      webbackend:
        aliases:
          - phpfpm
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  # Webstack NGINX
  nginx:
    image: nginx:alpine 
    labels:
      fluentd-tag: nginx
      co.elastic.logs/module: nginx 
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
      co.elastic.metrics/module: nginx
      co.elastic.metrics/hosts: "${data.host}:${data.port}"
    volumes:
      - web-conf:/etc/nginx/conf.d:ro
      - web-datas:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=yugo.mo-ot.fr
      - VIRTUAL_PORT=80
    networks:
      - webbackend
      - proxy-net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
  # Webstack VARNISH
  #varnish:
  #  image: jacksoncage/varnish
  #  links:
  #  - nginx:nginx
  #  volumes:
  #  - web-conf:/etc/varnish/
  #  volumes_from:
  #  - nginx:ro
  #  ports:
  #  - 80:80
